package com.wiktyl;

import org.python.util.PythonInterpreter;

import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.*;
import java.text.DecimalFormat;

public class InputForm {
    public JPanel rootPanel;
    private JTextField koszt_tf;
    private JTextField trudnosc_tf;
    private JButton submit_btn;
    private JLabel wynik_label;
    private JTextField dlugosc_tf;
    private JButton zPlikuButton;
    private JFileChooser fileChooser;

    public InputForm() {
        submit_btn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                DecimalFormat df = new DecimalFormat("0.00");
                wynik_label.setText("Ocena: " + df.format(Ocena.score) + "(dobry projekt)");
            }
        });
        zPlikuButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                JFileChooser fc = new JFileChooser();
                int return_value = fc.showOpenDialog(rootPanel);
                if (return_value == JFileChooser.APPROVE_OPTION) {
                    File selected_file = fc.getSelectedFile();
                    System.out.println(selected_file.getAbsolutePath());
                    Process p = null;
                    try {
                        //idk how to repair it, bug still exists
                        if (selected_file.getAbsolutePath().contains(" ")) {
                            File new_file = new File(selected_file.getAbsolutePath().replace(" ", "_"));
                            if (new_file.exists()) {
                                throw new IOException("file exists");
                            }
                            boolean success = selected_file.renameTo(new_file);
                            System.out.println(selected_file.getAbsolutePath());
                            System.out.println(new_file.getAbsolutePath());
                            p = Runtime.getRuntime().exec("python3 src/com/wiktyl/main.py" + " " + new_file.getAbsolutePath());
                        } else {
                            p = Runtime.getRuntime().exec("python3 src/com/wiktyl/main.py" + " " + selected_file.getAbsolutePath());
                        }
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                    BufferedReader in = new BufferedReader(new InputStreamReader(p.getInputStream()));
                    String ret = null;
                    try {
                        ret = in.readLine();
                        System.out.println(ret);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                    if (!ret.equals("OK")) {
                        JFrame frame = new JFrame();
                        JOptionPane.showMessageDialog(frame, "Podany plik jest błędny.");
                    }
                }
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(8, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Wprowadź koszt projektu (0 - ...)");
        rootPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        koszt_tf = new JTextField();
        rootPanel.add(koszt_tf, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Wprowadź trudność projektu (0 - 10)");
        rootPanel.add(label2, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        submit_btn = new JButton();
        submit_btn.setMargin(new Insets(0, 0, 0, 0));
        submit_btn.setText("Potwierdź");
        rootPanel.add(submit_btn, new com.intellij.uiDesigner.core.GridConstraints(6, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        wynik_label = new JLabel();
        wynik_label.setText("Kliknij potwierdź aby uzyskać ocenę projektu albo z piku");
        rootPanel.add(wynik_label, new com.intellij.uiDesigner.core.GridConstraints(7, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        trudnosc_tf = new JTextField();
        trudnosc_tf.setMargin(new Insets(2, 6, 2, 6));
        rootPanel.add(trudnosc_tf, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Wprowadź długość projektu w miesiąch (0 - ...)");
        rootPanel.add(label3, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        dlugosc_tf = new JTextField();
        rootPanel.add(dlugosc_tf, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        zPlikuButton = new JButton();
        zPlikuButton.setText("Z pliku");
        rootPanel.add(zPlikuButton, new com.intellij.uiDesigner.core.GridConstraints(6, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

}
